source :rubygems

gem 'calabash-android', '>= 0.4.8'
gem 'calabash-cucumber', '>= 0.17.0'
gem 'chronic'
gem 'ruby-oci8'
gem 'activerecord', '3.2.13'
gem 'activerecord-oracle_enhanced-adapter', '1.4.2'
